name: PerWorldWhitelist
version: 1.1.2
main: thito.perworldwhitelist.PerWorldWhitelist
authors:
- BlueObsidian
commands:
  perworldwhitelist:
    description: Whitelist a world
    aliases:
    - "pww"
    - "ww"
    - "worldwhitelist"
    - "wwhitelist"
    - "worldw"
    - "perww"
    - "perworldw"
    - "pworldw"
    - "pworldwhitelist"
    - "pwwhitelist"
    - "perwwhitelist"
permissions:
  perworldwhitelist.admin:
    description: Allows you to access PerWorldWhitelist command.
    default: op